name: Rust

on:
  push:
    branches:
      - master
  pull_request:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Initialize Submodules
      run: git submodule update --init --recursive
    - name: Cache cargo registry
      uses: actions/cache@v1
      with:
        path: ~/.cargo/registry
        key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.toml') }}
    - name: Cache cargo index
      uses: actions/cache@v1
      with:
        path: ~/.cargo/git
        key: ${{ runner.os }}-cargo-index-${{ hashFiles('**/Cargo.toml') }}
    - name: Cache cargo build
      uses: actions/cache@v1
      with:
        path: target
        key: ${{ runner.os }}-cargo-build-target-${{ hashFiles('**/Cargo.toml') }}
    - name: Format
      run: cargo fmt --verbose
    - name: Clippy
      run: cargo clippy --all-features --all-targets -- -D warnings
    - name: Build
      run: cargo build --all-features --verbose
    - name: Run tests
      run: cargo test --all-features --verbose
    - name: Setup go
      uses: actions/setup-go@v1
      with:
        go-version: 1.13.x
    - name: Install LightStep Conformance Runner
      run: go get -u github.com/lightstep/lightstep-tracer-go github.com/opentracing/opentracing-go github.com/lightstep/conformance/ls_conformance_runner
    - name: Run LightStep Carrier Conformance Test
      run: $(go env GOPATH)/bin/ls_conformance_runner cargo run --features lightstep --example lightstep_conformance
